### ISSUE TITLE
Example for decodeByNameWithErrors

### ISSUE THREAD

**Issue by tkvogt** [haskell-streaming/streaming-cassava#2]
I am struggling how to get rid of the (MonadResource m) context from

readFile :: MonadResource m => FilePath -> ByteString m ()

when using:

import qualified Data.ByteString.Streaming as B
import Streaming.Cassava as S

 S.decodeWithErrors S.defaultDecodeOptions NoHeader (B.readFile path))
        :: MonadResource IO => Stream (Of (Either CsvParseException EdgeProperties)) IO (Either (CsvParseException, B.ByteString IO ()) ())

A little example would help a lot.

**Comment by ivan-m** [comment]
Use [`streaming-with`](http://hackage.haskell.org/package/streaming-with) instead; [`readFile`](https://github.com/michaelt/streaming-bytestring/issues/17) doesn't seem to play nicely with `streaming-cassava`.
